# -*- coding: utf-8 -*-
"""yolov5-sagemaker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nTcocTlAvfREXl8DGcjIGobLtJpew_zH
"""
import os
import tensorflow as tf
from tensorflow.keras import backend
from sagemaker.tensorflow import TensorFlowModel
import sagemaker
pip install sagemaker
pip install tensorflow
sagemaker_session = sagemaker.Session()
#ls

#!cd yolov5

#!git clone https://github.com/ultralytics/yolov5
#!cd yolov5
#!pip install -r requirements.txt
#!python export.py --weights yolov5l.pt --include saved_model --nms
#!mkdir export && mkdir export/Servo
#!mv yolov5l_saved_model export/Servo/1
#!tar -czvf model.tar.gz export
#!aws s3 cp model.tar.gz "s3://drivex-label/model.tar.gz"


model_data = 's3://trialreprex/model.tar.gz'
role = 'arn:aws:iam::920644990528:role/service-role/AmazonSageMaker-ExecutionRole-20230209T121706'

INSTANCE_TYPE = 'ml.m5.xlarge'
ENDPOINT_NAME = 'yolov5-reprex'

model = TensorFlowModel(model_data=model_data,
                        framework_version='2.8', role=role)


predictor = model.deploy(initial_instance_count=1, 
                         instance_type=INSTANCE_TYPE,
                         endpoint_name=ENDPOINT_NAME)




#import sagemaker

#endpoint_config_name = 'yolov5-reprex'
endpoint_name = 'yolov5-reprex'

#sagemaker_session.create_endpoint(endpoint_name=endpoint_name,
                                  #config_name=endpoint_config_name)






